from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PAPER_DIR = ROOT / "docs" / "paper"
JA_TEX = PAPER_DIR / "honen-shinran-shared-core-paper.tex"
EN_TEMPLATE_TEX = PAPER_DIR / "honen-shinran-shared-core-paper-en.template.tex"
EN_TEX = PAPER_DIR / "honen-shinran-shared-core-paper-en.tex"


GENERATED_NOTE = (
    "% Generated by scripts/build_english_tex_from_ja_tex.py.\n"
    "% Structural source: honen-shinran-shared-core-paper.tex.\n"
    "% English wording source: honen-shinran-shared-core-paper-en.template.tex.\n"
)


def structural_events(tex: str) -> list[str]:
    events: list[str] = []
    block_re = re.compile(
        r"\\(?P<section>section\*?|subsection\*?)\{"
        r"|\\begin\{(?P<env>figure|table)\}"
        r"|\\bibitem\{(?P<bib>[^}]+)\}",
        re.S,
    )
    for match in block_re.finditer(tex):
        if match.group("section"):
            events.append(match.group("section"))
            continue
        if match.group("bib"):
            events.append(f"bibitem:{match.group('bib')}")
            continue
        env = match.group("env")
        end = tex.find(rf"\end{{{env}}}", match.start())
        if end == -1:
            raise ValueError(f"Unclosed {env} environment")
        block = tex[match.start() : end]
        label_match = re.search(r"\\label\{([^}]+)\}", block)
        label = label_match.group(1) if label_match else "NO_LABEL"
        events.append(f"{env}:{label}")
    return events


def label_sequence(tex: str, command: str) -> list[str]:
    return re.findall(rf"\\{command}\{{([^}}]+)\}}", tex)


def figure_paths(tex: str) -> list[str]:
    return re.findall(r"\\includegraphics(?:\[[^]]*\])?\{([^}]+)\}", tex)


def figure_file_names(tex: str) -> list[str]:
    return [Path(path).name for path in figure_paths(tex)]


def validate_alignment(ja_tex: str, en_tex: str) -> None:
    checks = [
        ("document events", structural_events(ja_tex), structural_events(en_tex)),
        ("labels", label_sequence(ja_tex, "label"), label_sequence(en_tex, "label")),
        ("bibitems", label_sequence(ja_tex, "bibitem"), label_sequence(en_tex, "bibitem")),
        ("figure file names", figure_file_names(ja_tex), figure_file_names(en_tex)),
    ]
    for name, ja_values, en_values in checks:
        if ja_values != en_values:
            for index, (ja_value, en_value) in enumerate(zip(ja_values, en_values), start=1):
                if ja_value != en_value:
                    raise ValueError(
                        f"{name} mismatch at {index}: Japanese={ja_value!r}, English={en_value!r}"
                    )
            raise ValueError(
                f"{name} length mismatch: Japanese={len(ja_values)}, English={len(en_values)}"
            )


def build() -> None:
    ja_tex = JA_TEX.read_text(encoding="utf-8")
    en_template = EN_TEMPLATE_TEX.read_text(encoding="utf-8")
    validate_alignment(ja_tex, en_template)

    en_tex = en_template
    en_tex = re.sub(r"^(% Generated by .*\n% Structural source: .*\n% English wording source: .*\n)+", "", en_tex)
    EN_TEX.write_text(GENERATED_NOTE + en_tex, encoding="utf-8")
    print(f"Wrote {EN_TEX.relative_to(ROOT)}")


if __name__ == "__main__":
    build()
